config/routes.rb
Rails.application.routes.draw do

  root 'static#welcome'
  
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :companies
  resources :job_postings

end

app/models/job_posting.rb
class JobPosting < ActiveRecord::Base
  belongs_to :company
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy]

  # GET /job_postings
  # GET /job_postings.json
  def index
    @job_postings = JobPosting.includes(:company).all
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
  end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new
  end

  # GET /job_postings/1/edit
  def edit
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)
    set_company
    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_postings/1
  # PATCH/PUT /job_postings/1.json
  def update
    set_company
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting.destroy
    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_posting_params
      params.require(:job_posting).permit(:job_title, :description, :company_id, :posting_date, :posting_url, :is_filled, :company_attributes => [:company_name, :location, :industry])
    end

    def set_company
      # Do not run the following code if the current Job Posting record already has a Company ID and it's unchanged from what's in the params.
      # If these are both true, there is already an associated Company value, and it does not need to be changed.
      # If these are not both true, it either means we do not have a Company value and we mean to associate one, or we are changing or removing the associated Company.
      unless @job_posting.company_id && @job_posting.company.company_name == params["job_posting"]["company"]["company_name"]
        # Do not run the following code if there is no Company Name params value.
        # If this is true, then that means we have an associated Company value that we wish to remove.
        # If this is not true, then we as associating either a new or existing Company value to this Job Posting.
        if !params["job_posting"]["company"]["company_name"]
          # Remove the Company associated with this Job Posting
          @job_posting.company_id = nil
        else
          # Associate the Company with the Job Posting
          @job_posting.company_id = find_company
        end
      end
    end

    def find_company
      # We are searching for an existing Company whose name matches the params value, if there is one.
      @job_posting_company ||= Company.find_by(company_name: params["job_posting"]["company"]["company_name"])
      # If we did not find an existing Company record matching that name...
      if !@job_posting_company
        # ...we will create one using the entered params.
        @job_posting_company = Company.create(
                                          company_name: params["job_posting"]["company"]["company_name"],
                                          location: params["job_posting"]["company"]["location"],
                                          industry: params["job_posting"]["company"]["industry"]
                                          )
        # @job_posting_company = Company.new(params["job_posting"]["company"])
        # @job_posting_company.save
      end
      # Return the Company record
      @job_posting_company.id
    end
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/job_postings/_form.html.erb
<%= form_for(@job_posting) do |f| %>
  <% if @job_posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>

      <ul>
      <% @job_posting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>





  <%= f.fields_for(:company) do |ff| %>
    <div>
      <%= ff.label :company_name %><br>
      <%= ff.text_field :company_name %>
    </div>
    <div>
      <%= ff.label :location %><br>
      <%= ff.text_field :location %>
    </div>
    <div>
      <%= ff.label :industry %><br>
      <%= ff.text_field :industry %>
    </div>
  <% end %>




  <div class="field">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <%#= f.form_for :company do |ff| %>
    <!-- <div class="field"> -->
      <%#= ff.label :company_name %><br>
      <%#= ff.number_field :company_name %>
    <!-- </div> -->
  <%# end %>
  <div class="field">
    <%= f.label :posting_date %><br>
    <%= f.date_select :posting_date %>
  </div>
  <div class="field">
    <%= f.label :posting_url %><br>
    <%= f.text_field :posting_url %>
  </div>
  <div class="field">
    <%= f.label :is_filled %><br>
    <%= f.check_box :is_filled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_postings/edit.html.erb
<h1>Editing Job Posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_posting %> |
<%= link_to 'Back', job_postings_path %>

app/views/job_postings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Job Postings</h1>

<table>
  <thead>
    <tr>
      <th>Posting Date</th>
      <th>Title</th>
      <th>Description</th>
      <th>Company</th>
      <th>URL</th>
      <!-- <th>Applied For?</th> -->
      <!-- <th>Was Rejected</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_postings.each do |job_posting| %>
      <tr>
        <td><%= job_posting.posting_date %></td>
        <td><%= job_posting.job_title %></td>
        <td><%= job_posting.description %></td>
        <td><%= job_posting.company.nil? ? "" : job_posting.company.company_name %></td>
        <td><%= link_to "Link", job_posting.posting_url %></td>
        <!-- <td><%#= job_posting.is_applied_for %></td> -->
        <!-- <td><%#= job_posting.is_rejected %></td> -->
        <td><%= link_to 'Show', job_posting %></td>
        <td><%= link_to 'Edit', edit_job_posting_path(job_posting) %></td>
        <td><%= link_to 'Destroy', job_posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job posting', new_job_posting_path %>

app/views/job_postings/new.html.erb
<h1>New Job Posting</h1>

<%= render 'form' %>

<%= link_to 'Back', job_postings_path %>

app/views/job_postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job Title:</strong>
  <%= @job_posting.job_title %>
</p>

<% unless @job_posting.company_id.nil? %>

  <% unless @job_posting.company.company_name.nil? %>
    <p>
      <strong>Company Name:</strong>
      <%= @job_posting.company.company_name %>
    </p>
  <% end %>

  <% unless @job_posting.company.location.nil? %>
    <p>
      <strong>Location:</strong>
      <%= @job_posting.company.location %>
    </p>
  <% end %>

  <% unless @job_posting.company.industry.nil? %>
    <p>
      <strong>Industry:</strong>
      <%= @job_posting.company.industry %>
    </p>
  <% end %>

<% end %>

<p>
  <strong>Job Description:</strong>
  <%= @job_posting.description %>
</p>

<p>
  <strong>Posting Date:</strong>
  <%= @job_posting.posting_date %>
</p>

<p>
  <strong>Posting URL:</strong>
  <%= link_to "Link", @job_posting.posting_url %>
</p>

<p>
  <strong>Is Filled:</strong>
  <%= @job_posting.is_filled %>
</p>


<%= link_to 'Edit', edit_job_posting_path(@job_posting) %> |
<%= link_to 'Back', job_postings_path %>